"""add datetime to order

Revision ID: 43fb82d7fcd9
Revises: 0859cdee13b5
Create Date: 2024-11-04 18:56:50.416576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fb82d7fcd9'
down_revision = '0859cdee13b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
